# Generated by Django 5.2.1 on 2025-09-09 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, help_text='可选的用户唯一标识', max_length=255, null=True, verbose_name='用户标识')),
                ('platform', models.CharField(choices=[('ios', 'iOS App Store'), ('android', 'Google Play Store'), ('windows', 'Microsoft Store'), ('macos', 'Mac App Store')], max_length=20, verbose_name='平台')),
                ('product_type', models.CharField(choices=[('monthly', '月费订阅'), ('yearly', '年费订阅'), ('lifetime', '终身购买')], max_length=20, verbose_name='产品类型')),
                ('product_id', models.CharField(max_length=255, verbose_name='产品ID')),
                ('transaction_id', models.CharField(max_length=255, unique=True, verbose_name='交易ID')),
                ('receipt_data', models.TextField(verbose_name='收据数据')),
                ('purchase_date', models.DateTimeField(verbose_name='购买时间')),
                ('expiry_date', models.DateTimeField(blank=True, null=True, verbose_name='到期时间')),
                ('status', models.CharField(choices=[('pending', '待验证'), ('verified', '已验证'), ('failed', '验证失败'), ('expired', '已过期'), ('refunded', '已退款')], default='pending', max_length=20, verbose_name='状态')),
                ('verification_date', models.DateTimeField(blank=True, null=True, verbose_name='验证时间')),
                ('verification_response', models.TextField(blank=True, null=True, verbose_name='验证响应')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '支付记录',
                'verbose_name_plural': '支付记录',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id'], name='payment_ver_user_id_b3f799_idx'), models.Index(fields=['platform'], name='payment_ver_platfor_ee86f2_idx'), models.Index(fields=['transaction_id'], name='payment_ver_transac_4d9f9e_idx'), models.Index(fields=['status'], name='payment_ver_status_8a4e2e_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, unique=True, verbose_name='用户标识')),
                ('is_premium', models.BooleanField(default=False, verbose_name='是否为付费用户')),
                ('subscription_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='订阅类型')),
                ('subscription_expiry', models.DateTimeField(blank=True, null=True, verbose_name='订阅到期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('current_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_subscriptions', to='payment_verification.paymentrecord')),
                ('subscription_history', models.ManyToManyField(blank=True, related_name='user_subscriptions', to='payment_verification.paymentrecord')),
            ],
            options={
                'verbose_name': '用户订阅',
                'verbose_name_plural': '用户订阅',
            },
        ),
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_data', models.TextField(verbose_name='请求数据')),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='请求IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='用户代理')),
                ('is_successful', models.BooleanField(verbose_name='验证成功')),
                ('response_data', models.TextField(blank=True, null=True, verbose_name='响应数据')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('payment_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to='payment_verification.paymentrecord')),
            ],
            options={
                'verbose_name': '验证日志',
                'verbose_name_plural': '验证日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
